# Miner

## Problem

Given a 2D matrix with random numbers, and a certain amount of 0 in it, output a matrix of the same size where each cell contains the distance to the nearest 0.
The distance between 2 cells is defined as the minimum number of unit movements (left, right, up, down) necessary to go from one to the other.

### Input:
|   |   |   |
|---|---|---|
| 0 | 0  |0 |
| 0 | 1  |0 |
| 1 | 1  |1 |

### Output:
|   |   |   |
|---|---|---|
| 0 | 0  |0 |
| 0 | 1  |0 |
| 1 | 2  |1 |

### Input:
|   |   |   |
|---|---|---|
| 0 | 1  |1 |
| 1 | 1  |1 |
| 1 | 1  |1 |

### Output:
|   |   |   |
|---|---|---|
| 0 | 1  |2 |
| 1 | 2  |3 |
| 2 | 3  |4 |

## Solution

Different approaches:
1. Find the position of each 0 element and keep the position in memory O(N), then iterate through each element of the matrix and compute the distance to each 0 O(NP) where P is the number of 0 in the matrix. if P is high, the complexity will be too. if P is say 50% of N then complexity is basically O(N²)
2. Also start by finding the positions of the 0s and store them to a file, but this time, perform a BFS-like approach. 

    We start with a matrix with infinity everywhere and 0s only at 0 location. 
    
    Iteratively we pop the beginning of the file, find neighbors, update distance to 0 (if an element is X, then distance of neighbor to 0 is min(X, X_{neighbor}+1)), and add at the end of the file the neighbors (which can be further updated if a 0 came up).

    Using a file and not a file is iportant as this algorithm won't work if items closest to 0 aren't treated first.
    
    Complexity is closer to O(N), as BFS complexity is O(V+E) except here V= N and E < 4N (since each cell has max 4 neighbors and only 2 for the corners, 3 for the borders). henve V+E < N+4N <= 5N which is O(N)

In [1]:
import numpy as np


def is_valid_matrix_coordinates(mat: np.array, e: tuple[int, int]) -> bool:
    max_x, max_y = mat.shape

    if e[0] < 0 or e[0] >= max_x or e[1] < 0 or e[1] >= max_y:
        return False

    return True


def find_neighbors(mat: np.array, e: tuple[int, int]) -> list[tuple[int, int]]:
    neighbors = [(e[0] - 1, e[1]), (e[0] + 1, e[1]), (e[0], e[1] - 1), (e[0], e[1] + 1)]
    return [
        neighbor for neighbor in neighbors if is_valid_matrix_coordinates(mat, neighbor)
    ]


def dist_to_zero(mat: np.array, debug=False) -> np.array:
    # Initialize an array with zeroes where there are 0 and infinity everywhere else

    out = np.ones(mat.shape) * np.inf

    out[np.where(mat == 0)] = 0.0

    # Find the zeroes
    zeroes_coordinates = [list(x) for x in np.where(mat == 0)]

    zeroes_coordinates = [(x[0], x[1]) for x in np.array(zeroes_coordinates).T]

    # Iteratively visit neighbors with a BFS approach
    if debug:
        iteration = 0

    while len(zeroes_coordinates) > 0:
        if debug:
            print(f"Iteration #{iteration}")
            print(zeroes_coordinates)
            print(out, "\n")
            iteration += 1

        e = zeroes_coordinates.pop(0)

        neighbors = find_neighbors(mat, e)  # coordinates of the neighbors

        for neighbor in neighbors:
            if out[e[0], e[1]] < out[neighbor[0], neighbor[1]]:
                zeroes_coordinates.append(neighbor)

                out[neighbor[0], neighbor[1]] = out[e[0], e[1]] + 1

    return out


mat = np.array([[0, 1, 2], [0, 4, 5], [6, 7, 8]])
print(mat, "\n")
dist_to_zero(mat, debug=True)

[[0 1 2]
 [0 4 5]
 [6 7 8]] 

Iteration #0
[(0, 0), (1, 0)]
[[ 0. inf inf]
 [ 0. inf inf]
 [inf inf inf]] 

Iteration #1
[(1, 0), (0, 1)]
[[ 0.  1. inf]
 [ 0. inf inf]
 [inf inf inf]] 

Iteration #2
[(0, 1), (2, 0), (1, 1)]
[[ 0.  1. inf]
 [ 0.  1. inf]
 [ 1. inf inf]] 

Iteration #3
[(2, 0), (1, 1), (0, 2)]
[[ 0.  1.  2.]
 [ 0.  1. inf]
 [ 1. inf inf]] 

Iteration #4
[(1, 1), (0, 2), (2, 1)]
[[ 0.  1.  2.]
 [ 0.  1. inf]
 [ 1.  2. inf]] 

Iteration #5
[(0, 2), (2, 1), (2, 1), (1, 2)]
[[ 0.  1.  2.]
 [ 0.  1.  2.]
 [ 1.  2. inf]] 

Iteration #6
[(2, 1), (2, 1), (1, 2)]
[[ 0.  1.  2.]
 [ 0.  1.  2.]
 [ 1.  2. inf]] 

Iteration #7
[(2, 1), (1, 2), (2, 2)]
[[0. 1. 2.]
 [0. 1. 2.]
 [1. 2. 3.]] 

Iteration #8
[(1, 2), (2, 2), (2, 2)]
[[0. 1. 2.]
 [0. 1. 2.]
 [1. 2. 3.]] 

Iteration #9
[(2, 2), (2, 2), (2, 2)]
[[0. 1. 2.]
 [0. 1. 2.]
 [1. 2. 3.]] 

Iteration #10
[(2, 2), (2, 2)]
[[0. 1. 2.]
 [0. 1. 2.]
 [1. 2. 3.]] 

Iteration #11
[(2, 2)]
[[0. 1. 2.]
 [0. 1. 2.]
 [1. 2. 3.]] 



array([[0., 1., 2.],
       [0., 1., 2.],
       [1., 2., 3.]])